### ISSUE TITLE
Unable to install on Kodi 17.6

### ISSUE THREAD

**Issue by montex** [luivit/plugin.video.rivedila7#25]
Installing the plugin through the Kodi interface does not work on version 17.6. A message complaining about the missing dependence of plugin `inputstream.adaptive` appears. However, it seems that such plugin only exists in Kodi 18+.

Just cloning the repository in the `~/.kodi/addons` folder worked for me, the plugin is running fine.

**Comment by Testato** [comment]
Witch OS ?
Our La7 plugin can install/activate
Inputstream.adaptive, but it must be present in the repository of your kodi installation.
Check in your "Install from repo - Inputstream videoplayer" here should be present inputstream.adaptive

Probably in your OS this is not present, you can install it manually for example on Linux 

On last Kodi 18.4 seems that inputstream.adaptive is completely integrated in Kodi, for example I do not see it on Android but the installation of La7 plugin do not fail

**Comment by montex** [comment]
I am using Linux (Debian 10). Kodi is installed from the official Debian repository, and the the "normal" Kodi repository is installed and active.

I found some guides suggesting to look for "VideoPlayer InputStream" as you suggest, but I cannot find it in my installation. I think the problem is that that plugin only exists for Kodi 18 and later: https://kodi.wiki/view/Add-on:InputStream_Adaptive  Therefore it blocks the installation on previous versions.

On another computer I had installed the plugin correctly on 17.1, probably before this requirement was added. Anyways, what is that plugin for? As I mentioned, I just cloned this git repository in the addons folder, and it works perfectly without it (on 17.6). My suggestion is to check for Kodi version and only request inputstream.adaptive if it is Kodi 18 or later.

**Comment by Testato** [comment]
This plugin is better than the already kodi included ffmpeg. 
I start to use it when discover that some videi work regularly and other not.
You can found some video in some section that sometimes do not work, instead whit this plugin all alway work.

The problem is not on kodi version but on SO.
Inputstream was separated from kodi, and on the official Debian tepo Kodi is present but Inputstream not.
Try to install the official Kodi repo (on ubuntu this is done by official ppa) and after reinstall Kodi. 
At least this worked from Kodi 17 to 18.2
For 18.4 something was changed again

**Comment by montex** [comment]
Hello,

I have just tested it with the Ubuntu PPA for Trusty, which is the latest one having version 17 and it still does not work. I tried this on a clean installation on a virtual machine.

Initially I got exactly the same behavior, because the inputstream plugin was not enabled. After enabling it manually the installation of rivedila7 returns with an error. In this case, even cloning the plugin from the repository did not work.

Anyways, cloning the repository worked on my pc, this could be a workaround for people experiencing the same problem.

**Comment by Testato** [comment]
I think that on your pc is working only because something changed for Kodi 18.4
(Inputstream.adaptive completely integrated ?) I will investigate on it.

But on kodi 17 it is sure that all work, but for linux (only some distro) you need install adaptive.stream manually by sudo apt install inputstream.adaptive (or someting else :-)

This command work if you have the official kodi ppa.
It is sure that our olugin work on kodi 17

Thanks for your issue and test

**Comment by Testato** [comment]
@montex 

May you try the new 4.0.0 version ?
It include an inputstream helper that automatically download it for you when needed

**Comment by montex** [comment]
Hello @Testato, 
I just tried it, it does not work on 17.6. It gives an error on selecting the plugin, before listing the available entries ("Rivedi La7" etc.). Please tell me if you need further information.
Version 3.10 works fine if installed manually. Only the live stream is not working, the rest is working fine.

As a suggestion, it would be helpful to tags in the repository to mark versions.

**Comment by Testato** [comment]
Inputstream in necessary now for Kive streaming because la7 website added DRM on live streaming.
So the only solution for you is install the last 18.5 version, because Drm is not supported on kodi 17.

If you do not found it in the Ubuntu/Debian repo you can download it from kodi.tv
